-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\fftTest\fftTest_tc.vhd
-- Created: 2022-11-29 23:35:20
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fftTest_tc
-- Source Path: fftTest_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_1_1   : identical to clk_enable
-- enb_1_1024_0: 1024x slower than clk with last phase
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY fftTest_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_1_1                         :   OUT   std_logic;
        enb_1_1024_0                      :   OUT   std_logic
        );
END fftTest_tc;


ARCHITECTURE rtl OF fftTest_tc IS

  -- Signals
  SIGNAL count1024                        : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL comp_0_tmp                       : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL enb_1_1024_0_1                   : std_logic;

BEGIN
  enb <= clk_enable;

  enb_1_1_1 <= clk_enable;

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 1023
  counter_1024_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      count1024 <= to_unsigned(16#001#, 10);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF clk_enable = '1' THEN
        count1024 <= count1024 + to_unsigned(16#001#, 10);
      END IF;
    END IF;
  END PROCESS counter_1024_process;


  
  comp_0_tmp <= '1' WHEN count1024 = to_unsigned(16#3FF#, 10) ELSE
      '0';

  phase_0_tmp <= comp_0_tmp AND clk_enable;

  phase_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_0 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_process;


  enb_1_1024_0_1 <= phase_0 AND clk_enable;

  enb_1_1024_0 <= enb_1_1024_0_1;

END rtl;

