vlib work
vcom  fftTest_pkg.vhd
vcom  FIR_Interpolation.vhd
vcom  fftTest_tc.vhd
vcom  SimpleDualPortRAM_generic.vhd
vcom  SDFCommutator1.vhd
vcom  RADIX22FFT_SDF1_1.vhd
vcom  RADIX22FFT_CTRL1_1.vhd
vcom  SDFCommutator2.vhd
vcom  RADIX22FFT_SDF2_2.vhd
vcom  RADIX22FFT_CTRL1_2.vhd
vcom  TWDLROM_3_1.vhd
vcom  Complex4Multiply.vhd
vcom  SDFCommutator3.vhd
vcom  RADIX22FFT_SDF1_3.vhd
vcom  RADIX22FFT_CTRL1_3.vhd
vcom  SDFCommutator4.vhd
vcom  RADIX22FFT_SDF2_4.vhd
vcom  RADIX22FFT_CTRL1_4.vhd
vcom  TWDLROM_5_1.vhd
vcom  Complex4Multiply_block.vhd
vcom  SDFCommutator5.vhd
vcom  RADIX22FFT_SDF1_5.vhd
vcom  RADIX22FFT_CTRL1_5.vhd
vcom  SDFCommutator6.vhd
vcom  RADIX22FFT_SDF2_6.vhd
vcom  RADIX22FFT_CTRL1_6.vhd
vcom  TWDLROM_7_1.vhd
vcom  Complex4Multiply_block1.vhd
vcom  SDFCommutator7.vhd
vcom  RADIX22FFT_SDF1_7.vhd
vcom  RADIX22FFT_CTRL1_7.vhd
vcom  SDFCommutator8.vhd
vcom  RADIX22FFT_SDF2_8.vhd
vcom  RADIX22FFT_CTRL1_8.vhd
vcom  TWDLROM_9_1.vhd
vcom  Complex4Multiply_block2.vhd
vcom  SDFCommutator9.vhd
vcom  RADIX22FFT_SDF1_9.vhd
vcom  RADIX22FFT_CTRL1_9.vhd
vcom  SDFCommutator10.vhd
vcom  RADIX22FFT_SDF2_10.vhd
vcom  RADIX22FFT_CTRL1_10.vhd
vcom  FFT.vhd
vcom  Sine_Wave.vhd
vcom  Sine_Wave1.vhd
vcom  fftTest.vhd
