-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\fftTest\Sine_Wave1.vhd
-- Created: 2022-11-30 00:07:34
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Sine_Wave1
-- Source Path: fftTest/Sine Wave1
-- Hierarchy Level: 1
-- 
-- Sine Wave
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.fftTest_pkg.ALL;

ENTITY Sine_Wave1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_1024_0                      :   IN    std_logic;
        Sine_Wave_out1                    :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END Sine_Wave1;


ARCHITECTURE rtl OF Sine_Wave1 IS

  -- Constants
  CONSTANT Lookup_Table3_table_data       : vector_of_signed16(0 TO 9) := 
    (to_signed(16#0000#, 16), to_signed(16#259E#, 16), to_signed(16#3CDE#, 16), to_signed(16#3CDE#, 16),
     to_signed(16#259E#, 16), to_signed(16#0000#, 16), to_signed(-16#259E#, 16), to_signed(-16#3CDE#, 16),
     to_signed(-16#3CDE#, 16), to_signed(-16#259E#, 16));  -- sfix16 [10]

  -- Signals
  SIGNAL address_cnt1                     : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Lookup_Table3_k                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL lut1out1                         : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 9
  Sine_Wave_addrcnt_temp_process1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      address_cnt1 <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_1024_0 = '1' THEN
        IF address_cnt1 >= to_unsigned(16#9#, 4) THEN 
          address_cnt1 <= to_unsigned(16#0#, 4);
        ELSE 
          address_cnt1 <= address_cnt1 + to_unsigned(16#1#, 4);
        END IF;
      END IF;
    END IF;
  END PROCESS Sine_Wave_addrcnt_temp_process1_process;


  
  Lookup_Table3_k <= to_unsigned(16#0#, 4) WHEN address_cnt1 = to_unsigned(16#0#, 4) ELSE
      to_unsigned(16#9#, 4) WHEN address_cnt1 >= to_unsigned(16#9#, 4) ELSE
      address_cnt1;
  lut1out1 <= Lookup_Table3_table_data(to_integer(Lookup_Table3_k));

  Sine_Wave_out1 <= std_logic_vector(lut1out1);

END rtl;

